CREATE SET TABLE job ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      Job_id INTEGER,
      Job_name CHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX ( Job_id );




CREATE SET TABLE job_dep ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      Job_id INTEGER,
      Job_dep_on INTEGER, 
CONSTRAINT fk FOREIGN KEY ( Job_id ) REFERENCES JOB ( Job_id ))
PRIMARY INDEX ( Job_id );




CREATE MULTISET TABLE job_log ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      Job_id INTEGER,
      Job_name CHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      Job_strt_time TIMESTAMP(0),
      Job_end_time TIMESTAMP(0),
      Job_status CHAR(80) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( Job_id );
